name: Test
run-name: ${{ github.actor }} is checking they haven't broken anything
on: [push]
jobs:
  Compile-And-Run-The-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile the code
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
